language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_faliures:
    - php: nightly

before_install:
  - travis_retry composer self-update
  - travis_retry composer validate

install:
  - travis_retry composer install

script:
  - vendor/bin/phpunit
